[package]
name = "two_percent"
version = "0.11.27"
authors = [
    "Zhang Jinzhou <lotabout@gmail.com>",
    "Robert Swinford <robert.swinford <...at...> gmail.com>",
]
description = "Fuzzy Finder in rust!"
documentation = "https://docs.rs/skim"
homepage = "https://github.com/kimono-koans/two_percent"
repository = "https://github.com/kimono-koans/two_percent"
readme = "README.md"
keywords = ["fuzzy", "menu", "util"]
license = "MIT"
edition = "2018"

[lib]
name = "skim"
path = "src/lib.rs"

[[bin]]
name = "sk"
path = "src/bin/main.rs"

[dependencies]
regex = { version = "1.10.6", default-features = false, features = [
    "unicode-perl",
    "unicode-case",
] }
shlex = { version = "1.3.0", optional = true, default-features = false }
unicode-width = { version = "0.1.13", default-features = false }
log = { version = "0.4.22", default-features = false }
env_logger = { version = "0.11.5", optional = true }
clap = { version = "3.2.25", optional = true, default-features = false, features = [
    "std",
    "cargo",
] }
tuikit = { version = "0.5.0", default-features = false }
vte = { version = "0.13.0", default-features = false }
fuzzy-matcher = { version = "0.3.29", default-features = false, package = "fuzzy-muff" }
rayon = { version = "1.10.0", default-features = false }
derive_builder = { version = "0.20.1", default-features = false, features = [
    "alloc",
] }
bitflags = { version = "2.6.0", default-features = false }
crossbeam-channel = { version = "0.5.13", default-features = false, features = [
    "std",
] }
which = { version = "6.0.3", default-features = false }
libc = { version = "0.2.158", default-features = false }

[features]
default = ["cli"]
cli = ["dep:clap", "dep:shlex", "dep:env_logger"]
malloc_trim = []

[profile.release]
debug = false
